# Copyright (C) 2026 Amutable GmbH

config_version = 1
cache_dir = "/var/lib/quarry-client/latest-metadata"
#include = ["/etc/quarry-client.conf.d/*.conf"] # TODO: Implement drop-ins.

# Official AmutableOS update repository.
[repo."updates.example.com/alpha"]
root_trust = { type = "bundled", path = "/usr/share/amutable-os/quarry/trusted/%eR-root.json" }
meta_root_url = "https://updates.example.com/alpha"
data_root_url = "https://updates.example.com/update"

# Per-machine repository.
[repo."userdata.example.com/tenant/machine/%m"]
root_trust = "insecure-tofu" # TODO: Make this use the TPM-encrypted trust model.
meta_root_url = "https://userdata.example.com/tenant/machine-id/%m"
data_root_url = "https://web-dashboard-183175217918.europe-west1.run.app/repos/machine-id/%m"
