version: "2"

run:
  build-tags:
    - insecure # internal/keystore/internal
    - http # cmd/quarry-client/http.go

linters:
  enable:
    - asasalint
    - asciicheck
    - containedctx
    - contextcheck
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - godot
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - musttag
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - usetesting
  settings:
    forbidigo:
      forbid:
        # Lexical path operations are _very_ dangerous to use.
        - pattern: ^filepath\.(Join|Clean|Glob|Split|Dir|Base|Abs|EvalSymlinks|Rel|Walk(|Dir))$
          pkg: ^path/filepath$
        # These operations all can lead to accidentally reaeding or writing
        # outside of the expected directory. They can be used, with great care.
        - pattern: ^os\.(Open|Create|Truncate|(Write|Read|Open)File|(Remove|Mkdir)\w*|(Syml|L)ink|Ch(own|mod))$
          pkg: ^os$
        - pattern: ^exec.LookPath$
          pkg: ^os/exec$
        # unix.*at syscalls are similarly dangeorus.
        - pattern: ^unix\.\w*at$
          pkg: ^golang.org/x/sys/unix$
        # os.Is* doesn't handle wrapped error types, use errors.Is().
        - pattern: ^os\.Is(Exist|NotExist|Permission|Timeout)$
          pkg: ^os$
      analyze-types: true
    govet:
      enable:
        - nilness
    testifylint:
      enable-all: true

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - go.amutable.dev/quarry
