//go:build insecure

// Copyright (C) 2026 Amutable GmbH

package tufext_test

import (
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	tufmetadata "github.com/theupdateframework/go-tuf/v2/metadata"

	"go.amutable.dev/quarry/internal/keystore"
	_ "go.amutable.dev/quarry/internal/keystore/insecure"
	"go.amutable.dev/quarry/internal/tufext"
)

func TestRootBuilder_Sign_Basic(t *testing.T) {
	// With no roles pre-configured, Sign autogenerates a fresh key for every
	// top-level role, self-signs with the root key, and reports the newly
	// generated KeyIDs to the caller.
	ctx, store := openTestStore(t)

	builder := tufext.NewRootBuilder()
	meta, newKeyIDs, err := builder.Sign(ctx, store)
	require.NoError(t, err)
	require.NotNil(t, meta)

	assert.Equal(t, tufmetadata.ROOT, meta.Signed.Type)
	assert.Equal(t, tufmetadata.SPECIFICATION_VERSION, meta.Signed.SpecVersion)
	assert.Equal(t, int64(1), meta.Signed.Version)
	assert.True(t, meta.Signed.ConsistentSnapshot)

	// One fresh KeyID per top-level role.
	require.Len(t, newKeyIDs, len(tufmetadata.TOP_LEVEL_ROLE_NAMES))
	require.Len(t, meta.Signed.Roles, len(tufmetadata.TOP_LEVEL_ROLE_NAMES))
	for _, roleName := range tufmetadata.TOP_LEVEL_ROLE_NAMES {
		role, ok := meta.Signed.Roles[roleName]
		require.True(t, ok, "role %q should be present", roleName)
		assert.Equal(t, 1, role.Threshold)
		require.Len(t, role.KeyIDs, 1)
	}

	// All generated keys landed in the store and match the root.json Keys map.
	for _, keyID := range newKeyIDs {
		stored, err := store.GetKey(ctx, keyID)
		require.NoError(t, err)
		require.NotNil(t, stored)
		assert.Contains(t, meta.Signed.Keys, string(keyID))
	}

	// Self-signed by the single autogenerated root key.
	rootKeyID := meta.Signed.Roles[tufmetadata.ROOT].KeyIDs[0]
	require.Len(t, meta.Signatures, 1)
	assert.Equal(t, rootKeyID, meta.Signatures[0].KeyID)

	rootKey, err := store.GetKey(ctx, keystore.KeyID(rootKeyID))
	require.NoError(t, err)
	verifyTUFSignature(t, tufmetadata.ROOT, rootKey, meta)
}

func TestRootBuilder_Sign_ExpiryDefaultAndExplicit(t *testing.T) {
	// Expires defaults from RefTime + ExpireAfter when left zero, and survives
	// untouched when the caller sets it explicitly through RootType().
	ctx, store := openTestStore(t)

	expireAfter := 48 * time.Hour

	t.Run("Defaulted", func(t *testing.T) {
		builder := tufext.NewRootBuilder()
		builder.RefTime = fixedRefTime
		builder.ExpireAfter = expireAfter

		meta, _, err := builder.Sign(ctx, store)
		require.NoError(t, err)

		assert.True(t, meta.Signed.Expires.Equal(fixedRefTime.Add(expireAfter)),
			"Expires should be RefTime.Add(ExpireAfter); got %v", meta.Signed.Expires)
	})

	t.Run("ExplicitPreserved", func(t *testing.T) {
		builder := tufext.NewRootBuilder()
		builder.RefTime = fixedRefTime
		builder.ExpireAfter = expireAfter

		explicitExpires := fixedRefTime.Add(10 * 365 * 24 * time.Hour)
		builder.RootType().Expires = explicitExpires

		meta, _, err := builder.Sign(ctx, store)
		require.NoError(t, err)

		assert.True(t, meta.Signed.Expires.Equal(explicitExpires),
			"Expires should match the explicitly set value; got %v", meta.Signed.Expires)
	})
}

func TestRootBuilder_Sign_PreservesConfiguredRoles(t *testing.T) {
	// Roles the caller has already configured via AddRole must not be
	// regenerated by Sign -- only the missing roles are autogenerated.
	ctx, store := openTestStore(t)
	rootKey, rootID := generateInStore(ctx, t, store)

	builder := tufext.NewRootBuilder()
	_, err := builder.AddRole(tufmetadata.ROOT, 1, rootKey.Public)
	require.NoError(t, err)

	meta, newKeyIDs, err := builder.Sign(ctx, store)
	require.NoError(t, err)

	// Root role preserved.
	assert.Equal(t, []string{rootID}, meta.Signed.Roles[tufmetadata.ROOT].KeyIDs)
	assert.Equal(t, 1, meta.Signed.Roles[tufmetadata.ROOT].Threshold)

	// The three other top-level roles got autogenerated keys.
	expectedAutogen := len(tufmetadata.TOP_LEVEL_ROLE_NAMES) - 1
	assert.Len(t, newKeyIDs, expectedAutogen)
	for _, id := range newKeyIDs {
		assert.NotEqual(t, rootID, string(id), "root key must not be regenerated")
	}

	// The user-supplied root key must still be retrievable from the store
	// -- it must not have been unlinked by any cleanup/GC path.
	_, err = store.GetKey(ctx, keystore.KeyID(rootID))
	require.NoError(t, err)

	// Signed by the user-configured root key.
	require.Len(t, meta.Signatures, 1)
	assert.Equal(t, rootID, meta.Signatures[0].KeyID)
	verifyTUFSignature(t, tufmetadata.ROOT, rootKey, meta)
}

func TestRootBuilder_Sign_MultisigRoot(t *testing.T) {
	// A multisig root role must have every one of its keys produce a
	// signature on the final metadata.
	ctx, store := openTestStore(t)
	k1, id1 := generateInStore(ctx, t, store)
	k2, id2 := generateInStore(ctx, t, store)

	builder := tufext.NewRootBuilder()
	_, err := builder.AddRole(tufmetadata.ROOT, 2, k1.Public, k2.Public)
	require.NoError(t, err)

	meta, _, err := builder.Sign(ctx, store)
	require.NoError(t, err)

	rootRole := meta.Signed.Roles[tufmetadata.ROOT]
	assert.Equal(t, 2, rootRole.Threshold)
	assert.Equal(t, []string{id1, id2}, rootRole.KeyIDs)

	// Signatures are appended in KeyIDs order.
	require.Len(t, meta.Signatures, 2)
	assert.Equal(t, id1, meta.Signatures[0].KeyID)
	assert.Equal(t, id2, meta.Signatures[1].KeyID)

	verifyTUFSignature(t, tufmetadata.ROOT, k1, meta)
	verifyTUFSignature(t, tufmetadata.ROOT, k2, meta)
}

func TestRootBuilder_Sign_ExtraKeys(t *testing.T) {
	// extraKeys produce their own signatures ahead of the root-role keys,
	// and go-tuf verifies the signature from any root-trusted key.
	ctx, store := openTestStore(t)
	extra, extraID := generateInStore(ctx, t, store)

	builder := tufext.NewRootBuilder()
	meta, newKeyIDs, err := builder.Sign(ctx, store, extra)
	require.NoError(t, err)

	// The extra key was not generated by Sign, but all four top-level roles
	// still got autogenerated keys.
	assert.Len(t, newKeyIDs, len(tufmetadata.TOP_LEVEL_ROLE_NAMES))
	for _, id := range newKeyIDs {
		assert.NotEqual(t, extraID, string(id))
	}

	// Extra signature is appended first, then the root role's own key.
	rootKeyID := meta.Signed.Roles[tufmetadata.ROOT].KeyIDs[0]
	require.Len(t, meta.Signatures, 2)
	assert.Equal(t, extraID, meta.Signatures[0].KeyID)
	assert.Equal(t, rootKeyID, meta.Signatures[1].KeyID)
}

func TestRootBuilder_Sign_ExtraKeyIsRootKey_NotDoubleSigned(t *testing.T) {
	// When an extra key is already the root role's key, Sign's second loop
	// sees a valid signature already and does not sign again -- the final
	// metadata carries exactly one signature.
	ctx, store := openTestStore(t)
	rootKey, rootID := generateInStore(ctx, t, store)

	builder := tufext.NewRootBuilder()
	_, err := builder.AddRole(tufmetadata.ROOT, 1, rootKey.Public)
	require.NoError(t, err)

	meta, _, err := builder.Sign(ctx, store, rootKey)
	require.NoError(t, err)

	require.Len(t, meta.Signatures, 1)
	assert.Equal(t, rootID, meta.Signatures[0].KeyID)
}

func TestRootBuilder_Sign_IndependentOfBuilder(t *testing.T) {
	// Sign deep-copies the inner payload, so mutations to the returned
	// Metadata must not bleed back into the builder and vice versa.
	ctx, store := openTestStore(t)

	builder := tufext.NewRootBuilder()
	meta, _, err := builder.Sign(ctx, store)
	require.NoError(t, err)
	require.NotNil(t, meta.Signed.Roles[tufmetadata.TARGETS])

	// Capture the builder's state before any mutations so the assertions
	// below don't hard-code default values that might drift.
	origTargetsThreshold := builder.RootType().Roles[tufmetadata.TARGETS].Threshold
	origMetaVersion := meta.Signed.Version

	// (1) Mutations to the returned metadata do not bleed into the builder:
	// rewrite the targets role's threshold and drop a role entirely.
	meta.Signed.Roles[tufmetadata.TARGETS].Threshold = origTargetsThreshold + 99
	delete(meta.Signed.Roles, tufmetadata.SNAPSHOT)

	inner := builder.RootType()
	assert.Equal(t, origTargetsThreshold, inner.Roles[tufmetadata.TARGETS].Threshold)
	assert.Contains(t, inner.Roles, tufmetadata.SNAPSHOT)

	// (2) Mutations to the builder do not bleed into the already-signed
	// metadata.
	inner.Version = origMetaVersion + 99
	assert.Equal(t, origMetaVersion, meta.Signed.Version)
}

func TestRootBuilder_Sign_CleansUpGeneratedKeysOnError(t *testing.T) {
	// When Sign fails after autogenerating keys, the defer must unlink those
	// keys from the store so they do not accumulate on repeated failures.
	// Here the failure is forced by passing an extra key with a nonexistent
	// driver -- SignRole errors in the extraKeys loop, which runs after
	// autogeneration.
	ctx, store := openTestStore(t)
	badKey, badKeyID := generateInStore(ctx, t, store)
	badKey.Driver = "nonexistent"

	builder := tufext.NewRootBuilder()
	meta, newKeyIDs, err := builder.Sign(ctx, store, badKey)
	require.Error(t, err)
	assert.Nil(t, meta)
	assert.Nil(t, newKeyIDs)

	// Only the pre-existing bad key should remain; all four autogenerated
	// keys should have been unlinked.
	var remaining []keystore.KeyID
	for id, iterErr := range store.ListKeyIDs(ctx) {
		require.NoError(t, iterErr)
		remaining = append(remaining, id)
	}
	require.Len(t, remaining, 1)
	assert.Equal(t, keystore.KeyID(badKeyID), remaining[0])
}

func TestRootBuilder_Sign_MissingKeyInStore(t *testing.T) {
	// If a caller configures the root role with a keyID that is neither in
	// the Keys map nor in the store, Sign's implicit FillRoleKeys pass
	// surfaces ErrNoSuchKey -- and any keys autogenerated for the other
	// top-level roles must be cleaned up. This also exercises the defer
	// cleanup path for failures that happen between autogeneration and the
	// signing loops.
	ctx, store := openTestStore(t)

	builder := tufext.NewRootBuilder()
	missingID := "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
	inner := builder.RootType()
	inner.Roles = map[string]*tufmetadata.Role{
		tufmetadata.ROOT: {KeyIDs: []string{missingID}, Threshold: 1},
	}

	meta, newKeyIDs, err := builder.Sign(ctx, store)
	require.Error(t, err)
	assert.ErrorIs(t, err, keystore.ErrNoSuchKey) //nolint:testifylint // assert is fine for error path checks
	assert.Nil(t, meta)
	assert.Nil(t, newKeyIDs)

	// Every autogenerated key (targets, snapshot, timestamp) must have been
	// unlinked -- the store should be empty.
	var remaining []keystore.KeyID
	for id, iterErr := range store.ListKeyIDs(ctx) {
		require.NoError(t, iterErr)
		remaining = append(remaining, id)
	}
	assert.Empty(t, remaining)
}

func TestRootBuilder_Sign_BadGenerateKeyDriver(t *testing.T) {
	// If GenerateKey fails mid-autogen (here: unknown driver), Sign returns
	// the error with no metadata and nothing is left behind in the store.
	// This covers the defer path when the failure happens before autogen has
	// produced any keys.
	ctx, store := openTestStore(t)

	builder := tufext.NewRootBuilder()
	builder.GenerateKeyOpts = []keystore.GenerateOption{keystore.WithDriver("nonexistent")}

	meta, newKeyIDs, err := builder.Sign(ctx, store)
	require.Error(t, err)
	assert.Nil(t, meta)
	assert.Nil(t, newKeyIDs)

	var remaining []keystore.KeyID
	for id, iterErr := range store.ListKeyIDs(ctx) {
		require.NoError(t, iterErr)
		remaining = append(remaining, id)
	}
	assert.Empty(t, remaining)
}

func TestRootBuilder_Sign_SequentialSigns(t *testing.T) {
	// Calling Sign twice on the same builder must only autogenerate keys on
	// the first call -- the second call sees every top-level role already
	// populated and produces fresh signatures with no new keys. Serves as a
	// regression guard for the "unconditional regen" bug from a second angle.
	ctx, store := openTestStore(t)

	builder := tufext.NewRootBuilder()
	first, firstKeyIDs, err := builder.Sign(ctx, store)
	require.NoError(t, err)
	require.Len(t, firstKeyIDs, len(tufmetadata.TOP_LEVEL_ROLE_NAMES))

	second, secondKeyIDs, err := builder.Sign(ctx, store)
	require.NoError(t, err)
	require.NotNil(t, second)

	// No new keys on the second call; every role was already populated.
	assert.Empty(t, secondKeyIDs)

	// Role layout is identical across both calls.
	for _, roleName := range tufmetadata.TOP_LEVEL_ROLE_NAMES {
		assert.Equal(t, first.Signed.Roles[roleName].KeyIDs, second.Signed.Roles[roleName].KeyIDs,
			"role %q KeyIDs should be stable across Sign calls", roleName)
	}

	// Both metadata objects are independently signed by the same root key.
	require.Len(t, second.Signatures, 1)
	assert.Equal(t, first.Signatures[0].KeyID, second.Signatures[0].KeyID)
}
