#!/bin/bash

# Copyright (C) 2026 Amutable GmbH
# quarry-sysupdate -- a runner for sysupdate using quarry-client

set -Eeuo pipefail

function quarry-client() {
	run0 -u quarry -g quarry quarry-client "$@"
}

function info() {
	echo "[INFO]" "$@" >&2
}

function warn() {
	echo "[WARN]" "$@" >&2
}

# Use a special prefix for all of our "magic" behaviour.
SPECIAL_PREFIX=".zzz-quarry-special"

# Apply sysupdate.d/*.{feature,transfer} files before running sysupdate.
SYSUPDATE_PREFIX="$SPECIAL_PREFIX/sysupdate."

# Stash the existing volatile sysupdate.*.d files for cleanup.
# TODO: Actually implement that?
SYSUPDATE_BACKUP_DIR="/var/lib/quarry-sysupdate/sysupdate-backup"
backup_name="$(date --utc "+%s.%N")"
backup_dir="$SYSUPDATE_BACKUP_DIR/$backup_name"
info "Stash away old volatile sysupdate.* definitions to $backup_dir."
mkdir -p "$backup_dir"
find /run -maxdepth 1 -name "sysupdate.*" -print0 | \
	xargs -0r mv -vt "$backup_dir" --
ln -sf "$backup_name" "$SYSUPDATE_BACKUP_DIR/last"

# We need to patch transfer files to use Path=<our http bridge> for [Source].
function postinst_sysupdate() {
	local local_path="$1"
	# TODO: Compute this from our live config (in theory sysupdate should be
	# able to show this?).
	local proxy_url="http://127.0.0.1:555/"
	# FIXME: We don't have awk in the base image so we can't write a nice
	# script that only does this for [Source] regardless of the Path= format.
	sed -Ei 's|^Path=https?://.*|Path='"$proxy_url"'|' "$local_path"
}

readarray -t special_files < <(quarry-client list --format="%n::%R" | grep -F "$SPECIAL_PREFIX" || :)
for target in "${special_files[@]}"; do
	repo="${target##*::}"
	target_path="${target%::*}"
	local_path=
	postinst_command=
	case "$target_path" in
		"$SYSUPDATE_PREFIX"*)
			local_path="/run/${target_path#"$SPECIAL_PREFIX"/}"
			mkdir -p /etc/extensions
			postinst_command=postinst_sysupdate
			;;
		*)
			warn "Unsupported extension $target_path in repository $repo -- skipping."
			continue
			;;
	esac
	if [ -e "$local_path" ]; then
		# TODO: This should not happen, but if it does we will end up with lots
		# of unfortunate behaviour in the case of mixed files from different
		# repository states.
		rm -f "$local_path"
		info "Removing pre-existing $local_path."
	fi
	info "Pre-update install ($repo) $target_path ==> $local_path."

	# The quarry user does not have access to /run/sysupdate.d, so we need to
	# run this download process as root. Less than ideal, but better than
	# saving to some other path and renaming.
	command quarry-client fetch --repo="$repo" --output="$local_path" "$target_path"

	# Run the post-install command if applicable.
	[ -z "$postinst_command" ] || "$postinst_command" "$local_path"

	# Make sure the above command did not accidentally create new files in the
	# client cache with root ownership (this would only happen if the repo was
	# updated between the list and fetch commands).
	# TODO: It should be possible for quarry-client to have a --no-refresh
	# mode, but unfortunately go-tuf doesn't provide proper support for it...
	chown -R quarry:quarry "/run/quarry-client/cache/$repo"
done

# TODO: Figure out how to clean up transfer files no longer included in the
# repo but are still present on the local machine. Deleting them is easy but
# actually triggering a clean uninstall seems unclear...

# Run sysupdate for all components.
readarray -t components < <(/usr/lib/systemd/systemd-sysupdate components)
for component in "${components[@]}"; do
	flags=()
	# <default> is a dummy name that doesn't need a --component flag.
	[[ "$component" != "<default>" ]] && flags+=("--component=$component")
	info "Update component $component."
	/usr/lib/systemd/systemd-sysupdate "${flags[@]}" update
done

# TODO: Should we put this in a separate service / timer?
for component in "${components[@]}"; do
	flags=()
	# <default> is a dummy name that doesn't need a --component flag.
	[[ "$component" != "<default>" ]] && flags+=("--component=$component")
	info "Try-reboot with component $component."
	/usr/lib/systemd/systemd-sysupdate "${flags[@]}" reboot
done
